image: node:12.13.0

pages:
  stage: deploy
  script:
    - echo "waiting..."
  artifacts:
    paths:
      - public
  only:
    - master

server:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd ./server
    - dpl --provider=heroku --app=salty-garden-80295 --api-key=$HEROKU_API_KEY
  only:
    - master
