image: node:12.13.0

# compile_resume:
#   stage: build
#   image: timnn/texlive # use a Docker image for LaTeX from https://hub.docker.com/
#   script:
#     # build the pdf
#     - ls -la
#     - pdflatex ./public/resume/JonoAugustineResume.tex
#     # copy to images
#     - mv ./public/resume/JonoAugustineResume.pdf ./public/images
#   artifacts:
#     paths:
#       - ./public/images/JonoAugustineResume.pdf
#   only:
#     - master

pages:
  stage: deploy
  script:
    - cd ./site
    - npm install
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master

# deploy server
server:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd ./server
    - dpl --provider=heroku --app=salty-garden-80295 --api-key=$HEROKU_API_KEY
  only:
    - master
